theme: jekyll-theme-cayman
title: Cozy
description: Audiobooks on Linux
show_downloads: "true"
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
